# -*- coding: utf-8 -*-
"""CapStone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ymgdqjl13RCdNsut02n6SxbcYViYjFq1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as grd
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

data = pd.read_csv("/content/supermarket_sales.csv")

data.head()

data1 = data.copy()

data.isnull().sum()

data.duplicated().sum()

data.columns

data.columns.tolist()

data

data.describe()

data.dtypes

# Problem Statement:
# Detect and remove outliers in sales revenue using IQR and visualize the results using boxplots.


# Select Column (Revenue)
col = 'revenue'

# IQR Method for Outliers
Q1 = data[col].quantile(0.25)
Q3 = data[col].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# Removing outliers
data_clean = data[(data[col] > lower) & (data[col] < upper)]

plt.figure(figsize=(12,5))

# Before Outliers
plt.subplot(1,2,1)
sns.boxplot(y=data[col])
plt.title("Before Outlier Removal")

# After Outliers
plt.subplot(1,2,2)
sns.boxplot(y=data_clean[col])
plt.title("After Outlier Removal")
plt.suptitle("Outlier Detection and Removal using IQR")
plt.tight_layout()
plt.show()

# Problem Statement:
# To explore and analyze the distribution of sales revenue by handling missing values
# using mean imputation and visualizing the data using histogram and boxplot.
# The goal is to understand data patterns, variability, and detect potential outliers.

# Select Column (Revenue)

rev = data[['revenue']]
print("---" * 10)
print(f"Missing Values:\n{data.isnull().sum()}")
print("---" * 10)

# Fill missing values with mean
rev = rev.fillna(data.mean(numeric_only=True))

# Visualization
plt.figure(figsize=(12,5))

# Histogram
plt.subplot(1,2,1)
plt.hist(data['revenue'], bins=20)
plt.title("Sales Revenue Distribution (Histogram)")
plt.xlabel("Sales Revenue (USD)")
plt.ylabel("Frequency")
plt.xticks(rotation=45)
plt.grid()

# Boxplot
plt.subplot(1,2,2)
plt.boxplot(data['revenue'])
plt.title("Sales Revenue Distribution (Boxplot)")

plt.tight_layout()
plt.show()

# Problem Statement:
# To evaluate the performance of different product categories by aggregating
# total sales revenue and representing it through a bar chart. Furthermore,
# to analyze the proportion of each category in the dataset using a pie chart
# for better understanding of category distribution.

# Revenue by Sales in Category
category_sales = data.groupby('product_line')['revenue'].sum().sort_values(ascending=False)

# Choosing Colours
colors = ['steelblue','coral','mediumseagreen','gold','mediumpurple','lightcoral']

# Create Subplots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Category-wise Sales
ax1.bar(category_sales.index, category_sales.values, color=colors)
ax1.set(title="Category-wise Sales", xlabel="Category", ylabel="Total Sales")
ax1.tick_params(axis='x', rotation=45)

# Category Distribution
ax2.pie(category_sales, labels=category_sales.index, autopct='%1.1f%%', colors=colors)
ax2.set_title("Category Distribution")

plt.tight_layout()
plt.show()

# Problem Statement:
# To evaluate and compare the performance of different branches by analyzing
# total revenue, average transaction value, and customer footfall using grouped visualizations.
#  The objective is to identify the most profitable and operationally efficient branch.

# Revenue by Sales in Brances
branch = data.groupby('branch')['revenue'].agg(['sum', 'mean', 'count'])

# Choosing Colours
colors = ['steelblue', 'coral', 'mediumseagreen']

# Create Subplots
fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# Visualization
for ax, col, title, ylabel in zip(axes,
    ['sum', 'mean', 'count'],
    ['Total Revenue', 'Avg Transaction Value', 'Customer Footfall'],
    ['Revenue', 'Avg Revenue', 'No. of Transactions']):
    ax.bar(branch.index, branch[col], color=colors, edgecolor='white')
    ax.set(title=title, xlabel="Branch", ylabel=ylabel)

plt.suptitle("Branch Performance Analysis", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Problem Statement:
# To study the distribution of payment methods used by customers and assess
# their impact on total revenue and average transaction value. Use a pie chart
# for payment method share and a bar chart for revenue contribution per method.

# Revenue by Payement
payment = data.groupby('payment_method')['revenue'].agg(['count', 'sum'])

# Choosing Colours
colors  = ['steelblue', 'coral', 'mediumseagreen']

# Create Subplots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Payment Method Share
ax1.pie(payment['count'], labels=payment.index, autopct='%1.1f%%', colors=colors)
ax1.set_title("Payment Method Share")

# Payment Method Analysis
ax2.bar(payment.index, payment['sum'], color=colors, edgecolor='white')
ax2.set(title="Revenue by Payment Method", xlabel="Payment Method", ylabel="Total Revenue")

plt.suptitle("Payment Method Analysis", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Problem Statement:
# To identify peak shopping hours by extracting the hour from the time column
# and aggregating transaction count and revenue. Visualize hourly trends using
# a line chart and a day-vs-hour heatmap to uncover high-activity time windows
# for operational and marketing decisions.

# Formatting Day and hours
data['hour'] = pd.to_datetime(data['time'], format='mixed').dt.hour
data['day']  = pd.to_datetime(data['date'], format='mixed').dt.day_name()
day_order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
hourly    = data.groupby('hour')[['invoice_id', 'revenue']].agg({'invoice_id': 'count', 'revenue': 'sum'})

# Create Subplots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5))

# Line Chart: Hourly Trends
ax1.plot(hourly.index, hourly['invoice_id'], marker='o', color='steelblue', label='Transactions')
ax1.plot(hourly.index, hourly['revenue'],    marker='o', color='coral',     label='Revenue')
ax1.set(title="Hourly Transaction & Revenue Trends", xlabel="Hour of Day", ylabel="Count / Revenue")
ax1.legend()

# Heatmap: Day vs Hour
pivot = data.groupby(['day', 'hour'])['invoice_id'].count().unstack().reindex(day_order)
sns.heatmap(pivot, annot=True, fmt='d', cmap='YlOrRd', ax=ax2, linewidths=0.5)
ax2.set(title="Transaction Volume: Day vs Hour", xlabel="Hour of Day", ylabel="Day of Week")

plt.suptitle("Peak Shopping Hours Analysis", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Problem Statement:
# Compare spending patterns between male and female customers
# across different product lines to uncover category-specific preferences.

# Formatting Gender of Customers
gender_product = data.groupby(['gender_customer', 'product_line'])['revenue'].agg(['sum', 'mean']).reset_index()
pivot_sum = gender_product.pivot(index='product_line', columns='gender_customer', values='sum')
pivot_mean = gender_product.pivot(index='product_line', columns='gender_customer', values='mean')

# Create Subplots
fig, axes = plt.subplots(1, 3, figsize=(18, 7))

# Total Spending
pivot_sum.plot(kind='bar', ax=axes[0])
axes[0].set_title("Total Spending by Gender")
axes[0].set_xlabel("Product Line")
axes[0].set_ylabel("Total Revenue")
axes[0].tick_params(axis='x', rotation=45)

# Average Spending
pivot_mean.plot(kind='bar', ax=axes[1], colormap='Set2')
axes[1].set_title("Avg Transaction Value by Gender")
axes[1].set_xlabel("Product Line")
axes[1].set_ylabel("Average Revenue")
axes[1].tick_params(axis='x', rotation=45)

# Heatmap Plotting
sns.heatmap(pivot_mean, annot=True, fmt=".1f", cmap="coolwarm", ax=axes[2])
axes[2].set_title("Spending Heatmap")

plt.suptitle("Gender vs Product Line Spending Analysis", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Problem Statement:
# Compare revenue trends, preferred product lines, and customer types
# across different cities to guide regional strategy.

# Revenue by City
city_revenue = data.groupby('city')['revenue'].sum().sort_values(ascending=False)

# Product Line Preference by City
city_product = data.groupby(['city', 'product_line'])['revenue'].sum().unstack()

# Customer Type Distribution by City
city_customer = data.groupby(['city', 'customer_type'])['invoice_id'].count().unstack()

# Create Subplots
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Revenue by City
city_revenue.plot(kind='bar', ax=axes[0], color='steelblue')
axes[0].set_title("Total Revenue by City")
axes[0].set_xlabel("City")
axes[0].set_ylabel("Revenue")
axes[0].tick_params(axis='x', rotation=45)

# Product Preference
city_product.plot(kind='bar', ax=axes[1])
axes[1].set_title("Product Line Preference by City")
axes[1].set_xlabel("City")
axes[1].set_ylabel("Revenue")
axes[1].tick_params(axis='x', rotation=45)
axes[1].legend(title="Product Line", bbox_to_anchor=(1.05, 1))

# Customer Type Distribution
city_customer.plot(kind='bar', ax=axes[2], colormap='Set2')
axes[2].set_title("Customer Type Distribution by City")
axes[2].set_xlabel("City")
axes[2].set_ylabel("Number of Customers")
axes[2].tick_params(axis='x', rotation=45)

plt.suptitle("City-wise Business Insights", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Problem Statement:
# Compare transactions with high quantity vs low quantity
#  in terms of revenue efficiency and product mix.

# Create Quantity Segments (Splitting the Robust data)
threshold = data['quantity'].median()
data['quantity_segment'] = data['quantity'].apply(
    lambda x: 'High Quantity' if x > threshold else 'Low Quantity'
)

# Revenue Efficiency
efficiency = data.groupby('quantity_segment')['revenue'].agg(['mean', 'sum', 'count'])

# Product Mix
product_mix = data.groupby(['quantity_segment', 'product_line'])['revenue'].sum().unstack()

# Create Subplots
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Revenue Efficiency
efficiency['mean'].plot(kind='bar', ax=axes[0], color=['steelblue', 'coral'])
axes[0].set_title("Avg Revenue per Transaction")
axes[0].set_xlabel("Quantity Segment")
axes[0].set_ylabel("Average Revenue")

# Product Mix
product_mix.plot(kind='bar', stacked=True, ax=axes[1])
axes[1].set_title("Product Mix by Quantity Segment")
axes[1].set_xlabel("Quantity Segment")
axes[1].set_ylabel("Total Revenue")
axes[1].legend(title="Product Line", bbox_to_anchor=(1.05, 1))

plt.suptitle("High vs Low Quantity Transaction Analysis", fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Problem Statement:
# To build and evaluate a regression model that predicts sales revenue using features
# such as unit price, quantity, and customer rating, with the objective of
# understanding key drivers of revenue and assessing model performance.


# Selecting independent variables (features)
X = data[['unit_cost', 'quantity', 'rating']]

# Target variable (what we want to predict)
y = data['revenue']

# Splitting data into training (80%) and testing (20%)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Model Training
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(X_train, y_train)

# Predicting revenue on unseen test data
y_pred = model.predict(X_test)

# Model Evaluation
from sklearn.metrics import mean_squared_error, r2_score

# R² Score
print(f"R² Score : {r2_score(y_test, y_pred):.4f}")
print(f"RMSE : {(mean_squared_error(y_test, y_pred))**0.5:.4f}")

# Scatter plot comparing actual vs predicted values
sns.scatterplot(x=y_test, y=y_pred, alpha=0.5, color='steelblue')

# Reference line (perfect prediction line: y = x)
plt.axline((0, 0), slope=1, color='coral', linestyle='--', label='Perfect Fit')

# Labels and title
plt.title("Actual vs Predicted Revenue")
plt.xlabel("Actual Revenue")
plt.ylabel("Predicted Revenue")
plt.legend()

plt.show()

